# Generated by Django 2.2.14 on 2020-07-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('logo_image', models.SlugField(max_length=150)),
                ('website', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
